### PR TITLE
setup prettier

### PR DESCRIPTION
**Pull request by timsu92**
This PR locks everyone's Prettier settings and just leave Prettier as a dependency in `package.json` so that no one will lose it.

Do note that in order to take effect in `coc.nvim` in Vim, I include `.vim/coc-settings.json` as well. If you have that as your workspace config, please move it away first and merge them latter and DO NOT push it back unless it truly will be used by everyone.

### CODE REVIEW

**Comment by GNITOAHC** [comment]
Please make `.vim` as a ignore directory cause that config isn't required for every collaborator.
Thanks for the prettier settings for us.

**Comment by timsu92** [comment]
I suggest leaving it since nothing would be done if no editor settings made. I disabled another plugin as well so there would be no conflict between them.

**Comment by timsu92** [comment]
But... True, not everyone uses vim. Removing...

**Comment by timsu92** [comment]
@GNITOAHC OK!

**Review by GNITOAHC — COMMENTED** [review]
Checked

**Review by GNITOAHC — APPROVED** [review]
Approve merging

**Pull request merged**
